import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.GREENMESH_CONFIG = {
                HEALTH_ENDPOINT: "__HEALTH_ENDPOINT__",
                GPU_METRICS_ENDPOINT: "__GPU_METRICS_ENDPOINT__",
                THROUGHPUT_METRICS_ENDPOINT: "__THROUGHPUT_METRICS_ENDPOINT__"
              };
              window.FLEXLLAMA_CONFIG = window.GREENMESH_CONFIG;
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
